import { useParams } from "react-router";
import { Link } from "react-router";
import { useEffect, useState } from "react";
import "./rocket.css";
import Loader from "../../components/Loader/Loader";
import ErrorComp from "../../components/ErrorComp/ErrorComp";
import type { LauncherConfigDetail } from "../../types/detailTypes";
function Rocketdetail() {
  const [err, setErr] = useState(null);
  const [res, setRes] = useState<LauncherConfigDetail | null>();
  const { id } = useParams();
  useEffect(() => {
    fetch(`https://lldev.thespacedevs.com/2.3.0/launcher_configurations/${id}`)
      .then((response) => {
        if (response.status !== 200) {
          throw new Error(response.status);
        }
        return response.json();
      })
      .then((data) => {
        setRes(data);
      })
      .catch((error) => setErr(error.message));
  }, [id]);
  if (err) {
    return <ErrorComp big={true} statNumb={err} />;
  }
  if (!res) {
    return <Loader />;
  }
  return (
    <>
      <article className="rocket-launcherConfigContainer">
        <div className="rocket-configHeader">
          <div className="rocket-configTitle divStyle">
            <h1>{res.name}</h1>
            {res.variant && <em>{res.variant} </em>}
            {res.full_name && <span>{res.full_name} </span>}
            {res.manufacturer && (
              <span className="rocket-manufacturer">
                by {res.manufacturer.name}
                {res.manufacturer.abbrev && ` (${res.manufacturer.abbrev})`}
              </span>
            )}
          </div>
          <div className="rocket-configImage divStyle">
            {res.image?.image_url && (
              <img
                src={res.image.image_url}
                alt={res.name}
                className="launcherPic"
              />
            )}
          </div>
          <div className="rocket-configOverview divStyle">
            <h3>Overview</h3>
            {res.description && <p>{res.description}</p>}
            <span>Status: {res.active ? "Active" : "Retired"}</span>
            {res.reusable !== undefined && (
              <span>Reusable: {res.reusable ? "Yes" : "No"}</span>
            )}
            {res.maiden_flight && (
              <span>
                Maiden Flight:{" "}
                {new Date(res.maiden_flight).toLocaleDateString()}
              </span>
            )}
            {res.alias && <span>Also known as: {res.alias}</span>}
          </div>
        </div>
        <div className="rocket-flexcontainer">
          <div className="rocket-techSpecs rocket-config divStyle2">
            <h2>Technical Specifications</h2>
            {res.length !== null && (
              <div className="rocket-specItem divSmall">
                <strong>Length:</strong> {res.length} m
              </div>
            )}
            {res.diameter !== null && (
              <div className="rocket-specItem divSmall">
                <strong>
                  <span className="tooltip">
                    Max Diameter
                    <span className="tip">
                      The maximum width of the rocket at its widest point
                    </span>
                  </span>
                  :
                </strong>{" "}
                {res.diameter} m
              </div>
            )}
            {res.launch_mass !== null && (
              <div className="rocket-specItem divSmall">
                <strong>
                  <span className="tooltip">
                    Mass at Launch
                    <span className="tip">
                      Total weight of the rocket at liftoff, including fuel and
                      payload
                    </span>
                  </span>
                  :
                </strong>{" "}
                {res.launch_mass} T
              </div>
            )}
            {res.to_thrust !== null && (
              <div className="rocket-specItem divSmall">
                <strong>
                  <span className="tooltip">
                    Thrust at Liftoff
                    <span className="tip">
                      The force generated by the engines to lift the rocket off
                      the ground
                    </span>
                  </span>
                  :
                </strong>{" "}
                {res.to_thrust} kN
              </div>
            )}
            {res.min_stage !== null && (
              <div className="rocket-specItem divSmall">
                <strong>Stages:</strong>{" "}
                {res.min_stage === res.max_stage
                  ? res.min_stage
                  : `${res.min_stage} - ${res.max_stage}`}
              </div>
            )}
            {res.launch_cost !== null && (
              <div className="rocket-specItem divSmall">
                <strong>Launch Cost:</strong> $
                {res.launch_cost.toLocaleString()} USD
              </div>
            )}
          </div>

          <div className="rocket-payloadCapacities rocket-config">
            <h2>Payload Capacities</h2>
            {res.leo_capacity !== null && (
              <div className="rocket-capacityItem divSmall">
                <strong>
                  <span className="tooltip">
                    LEO
                    <span className="tip">
                      Low Earth Orbit - altitude of approximately 160 to 2,000
                      km above Earth&apos;s surface
                    </span>
                  </span>
                  :
                </strong>{" "}
                {res.leo_capacity} kg
              </div>
            )}
            {res.gto_capacity !== null && (
              <div className="rocket-capacityItem divSmall">
                <strong>
                  <span className="tooltip">
                    GTO
                    <span className="tip">
                      Geostationary Transfer Orbit - an elliptical orbit used to
                      reach geostationary orbit
                    </span>
                  </span>
                  :
                </strong>{" "}
                {res.gto_capacity} kg
              </div>
            )}
            {res.geo_capacity !== null && (
              <div className="rocket-capacityItem divSmall">
                <strong>
                  <span className="tooltip">
                    GEO
                    <span className="tip">
                      Geostationary Orbit - circular orbit 35,786 km above
                      Earth&apos;s equator where satellites match Earth&apos;s
                      rotation
                    </span>
                  </span>
                  :
                </strong>{" "}
                {res.geo_capacity} kg
              </div>
            )}
            {res.sso_capacity !== null && (
              <div className="rocket-capacityItem divSmall">
                <strong>
                  <span className="tooltip">
                    SSO
                    <span className="tip">
                      Sun-Synchronous Orbit - a polar orbit where the satellite
                      passes over any given point at the same local solar time
                    </span>
                  </span>
                  :
                </strong>{" "}
                {res.sso_capacity} kg
              </div>
            )}
            {res.apogee !== null && (
              <div className="rocket-capacityItem divSmall">
                <strong>
                  <span className="tooltip">
                    Apogee
                    <span className="tip">
                      The highest point reached in a sub-orbital flight
                      trajectory
                    </span>
                  </span>
                  :
                </strong>{" "}
                {res.apogee} km
              </div>
            )}
          </div>

          <div className="rocket-launchStatistics rocket-config">
            <h2>Launch Statistics</h2>
            {res.total_launch_count !== null && (
              <div className="rocket-statItem divSmall">
                <strong>Total Launches:</strong> {res.total_launch_count}
              </div>
            )}
            {res.successful_launches !== null && (
              <div className="rocket-statItem divSmall">
                <strong>Successful Launches:</strong> {res.successful_launches}
              </div>
            )}
            {res.failed_launches !== null && (
              <div className="rocket-statItem divSmall">
                <strong>Failed Launches:</strong> {res.failed_launches}
              </div>
            )}
            {res.consecutive_successful_launches !== null && (
              <div className="rocket-statItem divSmall">
                <strong>Consecutive Successful:</strong>{" "}
                {res.consecutive_successful_launches}
              </div>
            )}
            {res.pending_launches !== null && (
              <div className="rocket-statItem divSmall">
                <strong>Pending Launches:</strong> {res.pending_launches}
              </div>
            )}
          </div>

          {(res.successful_landings !== null ||
            res.attempted_landings !== null) && (
            <div className="rocket-landingStatistics rocket-config">
              <h2>Landing Statistics</h2>
              {res.attempted_landings !== null && (
                <div className="rocket-statItem divSmall">
                  <strong>Attempted Landings:</strong> {res.attempted_landings}
                </div>
              )}
              {res.successful_landings !== null && (
                <div className="rocket-statItem divSmall">
                  <strong>Successful Landings:</strong>{" "}
                  {res.successful_landings}
                </div>
              )}
              {res.failed_landings !== null && (
                <div className="rocket-statItem divSmall">
                  <strong>Failed Landings:</strong> {res.failed_landings}
                </div>
              )}
              {res.consecutive_successful_landings !== null && (
                <div className="rocket-statItem divSmall">
                  <strong>Consecutive Successful:</strong>{" "}
                  {res.consecutive_successful_landings}
                </div>
              )}
              {res.fastest_turnaround && (
                <div className="rocket-statItem divSmall">
                  <strong>
                    <span className="tooltip">
                      Fastest Turnaround
                      <span className="tip">
                        The shortest time between two launches using the same
                        rocket booster
                      </span>
                    </span>
                    :
                  </strong>{" "}
                  {res.fastest_turnaround}
                </div>
              )}
            </div>
          )}
        </div>
        <div className="rocket-configRelated">
          {res.families && res.families.length > 0 && (
            <>
              <h2>Rocket Families</h2>
              <div className="rocket-relatedSection">
                {res.families.map((family) => (
                  <div key={family.id} className="rocket-familyItem ">
                    <strong className="rocket-familyName ">
                      {family.name}
                    </strong>
                    {family.description && <p>{family.description}</p>}
                    {family.active !== undefined && (
                      <span className=" divSmall ">
                        Status: {family.active ? "Active" : "Retired"}
                      </span>
                    )}
                    {family.maiden_flight && (
                      <span className="divSmall">
                        Maiden Flight:{" "}
                        {new Date(family.maiden_flight).toLocaleDateString()}
                      </span>
                    )}

                    {family.total_launch_count !== null && (
                      <span className="divSmall">
                        Total Launches: {family.total_launch_count}
                      </span>
                    )}
                    {family.successful_launches !== null && (
                      <span className="divSmall">
                        Successful: {family.successful_launches}
                      </span>
                    )}
                    {family.failed_launches !== null && (
                      <span className="divSmall">
                        Failed: {family.failed_launches}
                      </span>
                    )}

                    {family.manufacturer && family.manufacturer.length > 0 && (
                      <div className="rocket-familyManufacturers divSmall">
                        <strong>Manufacturers:</strong>
                        {family.manufacturer.map((manu) => (
                          <div
                            key={manu.id}
                            className="rocket-familyManufacturersChilds divmall"
                          >
                            <span>
                              {manu.name}
                              {manu.abbrev && ` (${manu.abbrev})`}
                            </span>
                            {manu.id && (
                              <Link
                                to={`/Agency/${manu.id}`}
                                className="linkSmall"
                              >
                                View details
                              </Link>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </>
          )}

          {res.manufacturer && (
            <div className="rocket-config">
              <h2>Manufacturer</h2>
              <div className="rocket-manufacturerCard divStyle">
                {res.manufacturer.logo?.thumbnail_url && (
                  <img
                    src={res.manufacturer.logo.thumbnail_url}
                    alt={res.manufacturer.name}
                    className="rocket-manufacturerLogo"
                  />
                )}
                <div className="rocket-manufacturerInfo">
                  <strong>{res.manufacturer.name}</strong>
                  {res.manufacturer.abbrev && ` (${res.manufacturer.abbrev})`}
                  {res.manufacturer.type?.name && (
                    <span>Type: {res.manufacturer.type.name}</span>
                  )}
                  {res.manufacturer.country &&
                    res.manufacturer.country.length > 0 && (
                      <span>
                        Country:{" "}
                        {res.manufacturer.country.map((c) => c.name).join(", ")}
                      </span>
                    )}
                  {res.manufacturer.founding_year && (
                    <span>Founded: {res.manufacturer.founding_year}</span>
                  )}
                  {res.manufacturer.administrator && (
                    <span>Administrator: {res.manufacturer.administrator}</span>
                  )}
                </div>
                {res.manufacturer.description && (
                  <p>{res.manufacturer.description}</p>
                )}

                {res.manufacturer.id && (
                  <Link to={`/Agency/${res.manufacturer.id}`} className="link">
                    View agency details
                  </Link>
                )}
              </div>
            </div>
          )}

          {res.program && res.program.length > 0 && (
            <>
              <h2>Programs</h2>
              <div className="">
                {res.program.map((prog) => (
                  <div key={prog.id} className="rocket-programCard divStyle">
                    {prog.image?.thumbnail_url && (
                      <img src={prog.image.thumbnail_url} alt={prog.name} />
                    )}
                    <div className="rocket-programInfo">
                      <strong>{prog.name}</strong>
                      {prog.type?.name && <span>Type: {prog.type.name}</span>}
                      {prog.start_date && (
                        <span>
                          Started:{" "}
                          {new Date(prog.start_date).toLocaleDateString()}
                        </span>
                      )}
                      {prog.end_date && (
                        <span>
                          Ended: {new Date(prog.end_date).toLocaleDateString()}
                        </span>
                      )}
                    </div>
                    {prog.agencies && prog.agencies.length > 0 && (
                      <div className="rocket-programAgencies">
                        <strong>Agencies: </strong>
                        {prog.agencies.map((agency) => (
                          <span key={agency.id}>
                            {agency.name}
                            {agency.abbrev && ` (${agency.abbrev})`}
                          </span>
                        ))}
                      </div>
                    )}
                    {prog.id && (
                      <Link to={`/Program/${prog.id}`} className="link">
                        View program details
                      </Link>
                    )}
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
      </article>
    </>
  );
}
export default Rocketdetail;
